name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - name: Get list of changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
    - name: Install pipenv
      run: pip install --no-cache-dir pipenv
    - name: Install dev dependencies
      run: pipenv install --dev --deploy --ignore-pipfile
    - name: Run pre-commit on changed files
      run: >
        pipenv run pre-commit run
        --files ${{ steps.changed-files.outputs.all_changed_files }}
        --show-diff-on-failure --color=always
      env:
        PIP_USER: false
    - name: Run all tests
      run: pipenv run pytest -vv
